#!/bin/bash

# ------------------------------------
# SETUP
# ------------------------------------

# get location of this test file
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

# import the bash library for testing
source "$PROJECT_ROOT/bin/imageOptimBashLib"

# ------------------------------------
# TESTS
# ------------------------------------

function testWeCanRunTests () {
  assertEquals "foo" "foo"
}

# ------------------------------------
# RUN
# ------------------------------------

. "$PROJECT_ROOT/test/shunit2/src/shunit2"
