#!/bin/bash

# ------------------------------------
# LOCATE THIS SCRIPT
# ------------------------------------

CLI_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ------------------------------------
# IMPORT BASH LIBRARY
# ------------------------------------

source "${CLI_PATH}/imageOptimBashLib"

# ------------------------------------
# INGEST COMMAND LINE ARGUMENTS
# ------------------------------------

while [ "$1" != "" ]; do
  case $1 in
    -d | --directory )
      shift;
      DIRECTORY_OPTION="$1"
      ;;
    -a | --image-alpha )
      USE_IMAGE_ALPHA="true"
      ;;
    -j | --jpeg-mini )
      USE_JPEGMINI="true"
      ;;
    -q | --quit )
      QUIT_ON_COMPLETE="true"
      ;;
    -h | --help )
      usage;
      exit 0
      ;;
    -e | --examples )
      examples;
      exit 0
      ;;
    -v | --version )
      echo $VERSION;
      exit 0
      ;;
    * )
    usage
    exit 1
  esac
  shift
done

# ------------------------------------
# BEGIN PROCESSING
# ------------------------------------

init_temp_directory
prepare_images
run_image_alpha
run_jpegmini
run_image_optim
output_savings
replace_originals
clean
